name = "blanketCon 23"
author = "LemmaEOF, UltraStorm"
version = "0.1.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a6a1ae7d0a6ed5df936f4277e37fc321e260a852547bb3cfd104ee0157432fe"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.19.4"]
