name = "blanketCon 23"
author = "LemmaEOF, UltraStorm"
version = "0.1.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3eb9a38b22c02819aca7554b8c9da0f94d90de853d6ca48e5c96fac2cf7706d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.19.4"]
