name = "blanketCon 23"
author = "LemmaEOF, UltraStorm"
version = "0.1.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cc77df373712e2316af38c71c3da7f14317b56ec2f8d8a768ca1b8c2db938a6"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20"]
