name = "blanketCon 23"
author = "LemmaEOF, UltraStorm"
version = "1.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f5c3dba8aa051617a6aef58eff262cbef91b7f7c0a327796a1b9912c68e7be3"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.19.4"]
