name = "blanketCon 23"
author = "LemmaEOF, UltraStorm"
version = "0.1.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cac2ec642c7cb829bab96705a0c0095a46199c57a303adc90b3d0b5bdb5e69dc"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.19.4"]
