name = "blanketCon 23"
author = "LemmaEOF, UltraStorm"
version = "1.0.0+1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a67e702f6a594b4aacdb3bdf95e07d53a8408c1108e7f4c9b0d271bca885c0fb"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.19.4"]
